# Generated by Django 4.2.8 on 2023-12-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_details', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('vendor_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
